### ISSUE TITLE
Compat requests for 1.18

### ISSUE THREAD

**Issue by Warhand** [wendall911/TCIntegrations#1]
Here's a list of mods and materials I think would really benefit from tinkers construct compat, even if its something really simple like a copy of iron but with different stats.

I'd consider this initial list the main materials I feel like tinkers could use.

Beyond Earth:
-Desh
-Calorite
-Ostrum

The Undergarden:
-Cloggrum
-Froststeel
-Utherium crystals
-Forgotten ingots
-Twistytwig

Create:
-Zinc
-Brass
-Andesite alloy
-Rose quartz

Industrial reborn:
-Iridium
-Mixed metal alloy

Ars nouveau:
-Magebloom fiber
-Source gem
-Archwood planks/logs

AquaCulture:
-Neptunium

Alex's mobs:
-Straddlite
-Bone serpent tooth
-Crocodile scute
-Cave centipede leg
-Void worm mandible
-Void worm eye

Botania:
-Terrasteel
-Elementium
-Livingwood
-Livingstone
-Gaia spirit ingot

This list is of materials that would be nice, but aren't as important as the previous list.

Upgraded netherite:
(All of these examples already have special effects added by the mod itself, so theoretically you could just be able to use the existing tool effects added by Upgraded netherite.)
-golderite
-Blazerite
-Enderite
-Prismarite
-Witherite
-Spiderite
-Phanterite
-Featherite
-Corrupterite
-Ultimerite
-Creativerite

General materials:
-Uranium

Applied energistics 2:
-Certus quartz
-Fluix crystals

The Graveyard:
-Dark iron ingots

Blue skies:
-Moonstone crystals
-Pyrope crystals
-Aquite
-Diopside crystals
-Charoite
-Falsite
-Ventium
-Horizonite

Extended crafting:
-Luminessence
-Black iron
-Redstone ingot
-Ender ingot
-Enhanced ender ingot
-Crystaltine ingot
-The ultimate ingot

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #20
- [x] #23 
- [x] #24

**Comment by wendall911** [comment]
Comment from a Curseforge user:
Can you please add Terrasteel and Elementium from Botania? (Terrasteel would have stats similar to Netherite, have Mana 3 and weapons would launch an energy blast and Elementium would have stats better than steel, the Pixie effect like the tools from Botania made from Elementium, and Mana 2)

**Comment by wendall911** [comment]
Curseforge request:
ProjectE . you can add emc for cobalt . . .

**Comment by wendall911** [comment]
Curseforge request:
Hi! could you try to integrate Tcon with Epic Fight? While you can make the weapons function as Epic Fight weapons in the config, the majority of attributes and modifiers don't work. (E.G. the knockback modifier doesn't increase impact and Fire Aspect doesn't work). I'd really appreciate it if you found a way to integrate them. Thanks!

**Comment by wendall911** [comment]
Curseforge request:
Ars Novue, effects could be modifiers from the mods like increased damage or mana regen or max mana or some mods have done something like this in the past but increasing all spell magnitude

**Comment by wendall911** [comment]
Just FYI for anyone following this. I'll be researching integration for this. I'll likely start with expanding Botania support, then branch out into the other mods. That said, there are caveats:
1. Mod must be open-source, just did a BOP integration, and since they closed-source it, this was complete pain
2. All features will be configurable, or able to be disabled via configuration options to allow modpack creators to maintain balance
3. Prioritization will likely be a bit random due to limited author time, but will accept PR

**Comment by wendall911** [comment]
Created a wiki page to track the major features:
[Integration Request Status](https://github.com/wendall911/TCIntegrations/wiki/Integration-Request-Status)
