### ISSUE TITLE
Crash when botania isn't loaded

### ISSUE THREAD

**Issue by Ganpan14O** [wendall911/TCIntegrations#11]
[crash-2022-07-09_02.13.56-fml.txt](https://github.com/wendall911/TCIntegrations/files/9075968/crash-2022-07-09_02.13.56-fml.txt)

**Comment by wendall911** [comment]
Thank you for the report! I'll get a fix out for this today. I didn't do all the checks I needed if you don't have Botania loaded. I'll put a note here once it is released with a link to the new version. Sorry about that!

**Comment by wendall911** [comment]
Here you go: https://www.curseforge.com/minecraft/mc-mods/tcintegrations/files/3867227

I have a better testing process now for making sure that it loads without other integration mods. Thanks for the report, much appreciated.

This will also hide all recipes for anything related to Botania if the mod isn't present.
