### ISSUE TITLE
Shovels

### ISSUE THREAD

**Issue by Jamiebear** [wendall911/TCIntegrations#12]
Could you possibly add shovels as they were removed from tinkers construct during the massive overhaul of the mod

**Comment by wendall911** [comment]
I have very little interest in doing this. I know you've asked a couple times before. What is the fascination with shovels? It really isn't useful given there is the mattock, pickadze and excavator. I fail to see how it fits into any kind of gameplay. If you could explain some rationale for this, I might consider it. Given the long list of integrations already planned, this doesn't feel important at all without more information.

**Comment by wendall911** [comment]
Do you have anymore feedback for this? I'm still confused about why the three options for shovels isn't sufficient. https://github.com/SlimeKnights/TinkersConstruct/issues/4885 covers the issue pretty well. I will close this if I don't see any more information.
