### ISSUE TITLE
can't use brass to cast weapons

### ISSUE THREAD

**Issue by neonyxiaa** [wendall911/TCIntegrations#16]
You cant use molten brass to cast brass weapon parts

You can cast ingots and blocks though

**Comment by wendall911** [comment]
Thanks for the report. I'll fix and push an update up shortly.

**Comment by wendall911** [comment]
Sorry about missing this!  I added the casting recipes, should be good now. https://www.curseforge.com/minecraft/mc-mods/tcintegrations/files/3889864
