### ISSUE TITLE
(Create) Cannot repair Brass Pickaxe with Brass Ingots

### ISSUE THREAD

**Issue by spyfox321** [wendall911/TCIntegrations#22]
![image](https://user-images.githubusercontent.com/29081752/182281983-48d8b80d-d10a-49ba-89bd-3ba07022b6c1.png)
I am using this mod with Tinkers, Create and other smaller mods.
The Tinkers Pickaxe I made with a Brass pick head cannot be repaired with a Brass Ingot.

**Comment by wendall911** [comment]
Thanks for the report. I won't be able to fix this for a couple days, as I'm traveling. I'll fix as soon as I'm back.

**Comment by wendall911** [comment]
Ok, I added the proper data for the repair material. Appreciate the report!

https://www.curseforge.com/minecraft/mc-mods/tcintegrations/files/3918165
