### ISSUE TITLE
Mod breaks Tinkers Construct's bronze recipe

### ISSUE THREAD

**Issue by KnightMiner** [wendall911/TCIntegrations#29]
This mod currently adds its custom bronze recipe [at the same path as Tinkers' recipe](https://github.com/wendall911/TCIntegrations/blob/1.18.2/src/generated/resources/data/tconstruct/recipes/smeltery/alloys/molten_bronze.json). This causes it to override the proper bronze recipe even when the pack includes tin, which has lead to a ton of users being confused and thinking Tinkers is to blame for having a broken recipe. Please create that recipe under your own namespace so it does not delete our recipe.

Really in general, remove all your custom recipes from our namespace. There is no reason your mod should be creating recipes under `tconstruct` unless they are an override, create new recipes under your mod ID. All our datagenerators support you choosing a mod ID to generate your recipes. Do not use our `BaseRecipeProvider`, make your own using your own ID, literally the only purpose of that class is to [set the output mod ID](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/common/data/BaseRecipeProvider.java#L26-L29)

**Comment by wendall911** [comment]
Ok, will fix this and push something out soon. Thanks for pointing this out.

**Comment by wendall911** [comment]
I added a conditional for bronze to only show the alternate if zinc is missing. I also moved all recipes into the proper namespace.

**Comment by wendall911** [comment]
@KnightMiner One side note. I actually only intended this mod to be for 1.18.1 temporarily to be able to address overriding diamond/emerald modifiers, as there was no datagen yet, and a recipe for bronze without tin. However, after getting a ton of requests, I eventually added a bunch more stuff. I never did go back and clean up the bronze implementation. Apologies for causing the issue.
