### ISSUE TITLE
Malum Soul Stained Steel tools crashing game on equip

### ISSUE THREAD

**Issue by ianm1647** [wendall911/TCIntegrations#33]
I am playing on a modpack and decided to add in your mod as the modpack uses multiple mods that your mod supports, and coming across the Soul Stained Steel tools , the game crashes every time I equip one in my hand. It looks like it has something to do with the Soul Stained modifier in particular. ([Crash report](https://pastebin.com/q6fw44hT))

I have yet to test with the armor, but this is causing multiple problems like being unable to get into a world after having equipped this tool. If this could be fixed asap please, I know you may not have much time on your hands, and if thats the case take your time.

Also another request regarding Malum support, I have no idea if you have integrated the spirit harvesting aspect of Malum into the Soul Stained modifier, if not could you possibly add a separate modifier to apply this ability to tools. If you need a reference, you could look at the Crude Scythe in Malum or look at my mod, specifically this [class file](https://github.com/ianm1647/bettercompat/blob/main/src/main/java/com/bettercompat/main/modifiers/craftable/SpiritReaperModifier.java). You may be able to implement it better than I have, plus this was also for 1.16, so things could have changed.

Thank you for your time , hopefully you can come out with a fix sooner than later!

**Comment by moon-st0ne** [comment]
confirming this still has not been fixed

**Comment by wendall911** [comment]
Not yet, I'll get a fix out soon and post here.

**Comment by wendall911** [comment]
Quick update on this. Malum still has not released a latest fix. I'll do a release once it is out. Maybe in the next few days? I hope so.

**Comment by SammySemicolon** [comment]
I just discovered that this mod has malum compat, absolutely loving it.
Looking at it, doesn't look like the crash happens as of Malum version 1.5

As for making Soul Stained tcon tools spawn spirits on kill, you'd simply need to make them set the `MalumLivingEntityDataCapability.getCapability(target).soulData.exposedSoulData` variable to some number (malum does 200) when an enemy is struck

**Comment by wendall911** [comment]
@SammySemicolon Thanks for the help with this. I added tooltips when pressing Shift. Everything works well in my testing. Looking forward to playing with the updated version.
