### ISSUE TITLE
"Burst" from the Terra modifier doesn't seem to work

### ISSUE THREAD

**Issue by LeoBeliik** [wendall911/TCIntegrations#35]
> When swung and the attack recharge meter is full, it will use 100 Mana and create a damaging Mana burst that deals 7 points (3.5 hearts) of damage to the hit mob

Forge 40.2.1
Botania 1.18.2-435
TConstruct 1.18.2-3.6.3.111
TCIntegrations 1.18.2-2.0.15.0

tested it with a dagger, sword and broadsword, none of them shoots a burst, they do repair tho

Edit: it seems to be working, as in it does damage, but it's just invisible

**Comment by wendall911** [comment]
Yes, without a lot of extra work, burst will not have a visual effect.
