### ISSUE TITLE
Create Support

### ISSUE THREAD

**Issue by wendall911** [wendall911/TCIntegrations#4]
- Brass - Completed in create-integration branch
  - Alloy can be crafted in the forge
  - Material stats similar to bronze
  - Has new trait "Moderate" that makes the tool mine faster in moderate temperatures
  - Can be made into any tool part in the forge
- Engineer's Goggles ability
  - Can upgrade helmet with Engineer's Goggles
- Mechanical Arm ability
  - Adds ability to attack with any melee weapon in the offhand
- Andesite Alloy - In progress
  - Only has Ingot
  - No Fluid
  - Some type of upgrade modifier for this
- Zinc - It doesn't make sense to add this as a fluid (it barely made sense to do Brass)
  - Has Block/Ingot/Nugget
  - Has Fluid
- Rose quartz - Won't implement
  - Doesn't make any sense, this is just quartz and redstone, not sure what benefit there would be

**Comment by mlysle** [comment]
I use your mod with Materialis (https://www.curseforge.com/minecraft/mc-mods/materialis). Because both mods support Brass there are redundant items when running the mods together. As far as I know this is the only overlap between the two mods. It would be nice if one mod could prioritize the other. I'm asking here because materials support is the only focus of Materialis, whereas this is a general compatability mod.

**Comment by wendall911** [comment]
Thanks for reporting. I'll take a look. I can probably include some conditional logic if the mod is installed.

**Comment by wendall911** [comment]
@mlysle I think I should mark Materialis as incompatible. It wasn't available for months after 1.18 was released, and I didn't even realize it existed. What is really shocking is that it is way more popular (likely because it existed for 1.16) and it just released support for 1.18. I think a person should choose one or the other. Materialis is just for having a bunch of materials, and while I could disable some stuff, the integrations in this mod are actually thought out and implemented for modpack balance. Materialis should actually provide the mechanism to disable their integrations individually, as many don't add much if anything to the core concept.

For example, Botania support in TCIntegrations has several cool features. If I disable the materials in this mod, then you just get dumb materials integration, which isn't really very useful. Just simple stats and traits for a bunch of materials doesn't seem that useful.
