### ISSUE TITLE
Crashed on startup [Dawncraft v1.19_HF, Modded]

### ISSUE THREAD

**Issue by KusanagiRyu** [wendall911/TCIntegrations#41]
[crash-2023-06-09_22.01.49-client.txt](https://github.com/wendall911/TCIntegrations/files/11707055/crash-2023-06-09_22.01.49-client.txt)

**Comment by wendall911** [comment]
The attached report has nothing to do with this mod.

**Comment by wendall911** [comment]
The error attached is an Iris shader crash from client-side.

**Comment by KusanagiRyu** [comment]
Shader...OK... sorry and thanks.
