### ISSUE TITLE
[1.18.2] CRASH: Mod loading error has occurred

### ISSUE THREAD

**Issue by DeshiDesu** [wendall911/TCIntegrations#43]
**Installed Mods:**
>Forge 40.2.9
TCIntegrations-1.18.2-2.0.17.0.jar
TConstruct-1.18.2-3.6.4.113.jar
Mantle-1.18.2-1.9.45.jar

[crash-2023-06-10_14.08.57-fml.txt](https://github.com/wendall911/TCIntegrations/files/11713026/crash-2023-06-10_14.08.57-fml.txt)

**Comment by wendall911** [comment]
Thanks for the report. Not sure what is going on. I'll try and get out a fix today.

**Comment by wendall911** [comment]
Posting a new file on CF now. Sorry, I some development work that is in the new release of TCon go out in this build. Fix in 2.0.17.1. I'll remove the broken file. Have some support for bows and crossbows in this version, so worth the upgrade.

**Comment by DeshiDesu** [comment]
Thanks
