### ISSUE TITLE
Undergarden compatibility doesn't work

### ISSUE THREAD

**Issue by KreloX** [wendall911/TCIntegrations#47]
None of the undergarden materials can be smelted in the foundry. Tinker's parts and weapons made of these materials aren't registered.

Minecraft 1.18.2
TC Integrations version: 2.0.17.4
Tinker's version: 3.6.4.113
Undergarden version: 0.7.1

**Comment by wendall911** [comment]
You can make parts out of the mats? I didn't register any material stats, so this is working as intended. Only allow using the smeltery for melting. This isn't a materials for tool parts, with very few exceptions. You can use the materials for modifiers or abilities for the majority of the integrations.

![2023-08-05_07 25 48](https://github.com/wendall911/TCIntegrations/assets/44465/c8404388-b047-435d-8196-d5ed5bc1c7cc)

**Comment by wendall911** [comment]
If you don't see any parts listed in JEI for a material, no parts can be made with the material. It gets silly after a while adding materials, so this mod is about providing the capabilities on tools/weapons/armor that the mod has as an integration.

**Comment by wendall911** [comment]
Materials are smelting fine for me. Can you give a specific material that is an issue?

![2023-08-05_07 39 48](https://github.com/wendall911/TCIntegrations/assets/44465/1d312163-7239-4118-af43-0ac09594a8f2)

**Comment by wendall911** [comment]
Casting works as intended for nuggets, ingots and blocks. Let me know if there are any other issues. I'll leave this open, but I don't see an issue at all.

**Comment by KreloX** [comment]
Sorry, I still wasn't familiar with the new tinker's + newest version of JEI is behaving weird and REI doesn't work with tinkers at all, so I was confused. Sorry for bothering you.

**Comment by wendall911** [comment]
Oh, no problem. I don't mind taking a look. Hopefully it helps.
