### ISSUE TITLE
Linear Phantasmal damage increase

### ISSUE THREAD

**Issue by KermitEmperor** [wendall911/TCIntegrations#50]
I have been recently messing with the mod and it seems that my cleaver's phantasmal ghost sword projectile's damage is increasing with every hit by about 0.5 damage (1.18.2 latest)

Here is the applied modifiers on the weapon in case it affects it
![image](https://github.com/wendall911/TCIntegrations/assets/74988196/88e8a264-acac-4c44-b458-30f171abfcd0)

**Comment by wendall911** [comment]
Thanks for the report. Good timing, as I'm working on a 1.19.2 release now. I'll do some testing and see why it is stacking. Sounds very OP. Actually, that weapon looks OP as-is, lol.
