### ISSUE TITLE
Ice and Fire Dragonsteel only works for armor on new tcon 3 version

### ISSUE THREAD

**Issue by PhantomPicklettv** [wendall911/TCIntegrations#58]
Idk if im tweaking, but i sword that the Dragonsteel could be used for tools, but when i loaded the newest version of integrations up, there were only shields and armor for dragonsteel. Idk if this is a mistake but im curious

**Comment by wendall911** [comment]
It isn't a mistake. I really don't want this mod to be a materials mod. Really, just focused on integration. Having the armor material, and the weapon modifiers feels like the right fit. I may revisit this at some point, but for now it is only planned to have it be for armor.

**Comment by wendall911** [comment]
I think they had some integration at some point in 1.18.2, but it was pretty broken. I only did the modifiers. The molten dragonsteel stuff I just added from a user request, btw.

**Comment by PhantomPicklettv** [comment]
Fair enough, i was just wondering.
