### ISSUE TITLE
Ars Nouveau Support

### ISSUE THREAD

**Issue by wendall911** [wendall911/TCIntegrations#6]
- Magebloom fiber
  - Add new "Novice", "Mage" or "Archmage" modifier to armor
    - Uses mana to repair item by 1 every 200 ticks, costs 20 mana
    - Provides Mana Boost enchantment based on level
    - Provides Mana Regen enchantment based on level
- Source Gem
  - Fluid and smeltery recipes
- "Enchanter's Shield" modifier for Chestplates
  - Upon blocking damage, the user will gain a short duration of Mana Regeneration and Spell Damage.
  - Uses mana to repair item by 1 every 200 ticks, costs 20 mana

**Comment by AbsorbingSafe11** [comment]
Could the Enchanter's Shield  be used to make an armor modifier that adds a similar effect as the shield in just the chestplate? 
As for the Novice and Mage modifiers could you make special items that work as modifier types? (like melted mana stones poured on to a plate)
