### ISSUE TITLE
[1.19.2] Engineer's Goggles gives Ability slots instead of working like the Create googles 

### ISSUE THREAD

**Issue by ffuentesm** [wendall911/TCIntegrations#60]
TCIntegrations-1.19.2-2.0.21.5
TConstruct-1.19.2-3.8.3.39
Forge: 43.3.0

When I try to check the stress and fluid tanks, the modifier does nothing. I can't see the stress capacity of anything. 
![image](https://github.com/wendall911/TCIntegrations/assets/44974827/71bb8ce4-7bd0-4993-88da-01b0754efe6a)

Also, the modifier gives an extra ability slot to the helmet. 
![image](https://github.com/wendall911/TCIntegrations/assets/44974827/c200c179-73a4-4b5a-b702-5a147ba0f630) 
![image](https://github.com/wendall911/TCIntegrations/assets/44974827/51befbff-3bc1-4f27-906a-87e0c3573116)

**Comment by wendall911** [comment]
Ok, certainly a bug. I'll test and get a fix out soon.

**Comment by wendall911** [comment]
Fixed in the latest 1.19.2-2.0.21.6
