### ISSUE TITLE
[1.19.2] This mod causes the Osmium book material entry shows two traits and an error

### ISSUE THREAD

**Issue by ffuentesm** [wendall911/TCIntegrations#61]
You can see the error page here : https://github.com/SlimeKnights/TinkersConstruct/issues/5237#issue-2345239858

Log: https://pastebin.com/BR8FaQ2P

This only appears when TIntegrations is installed 
![image](https://github.com/wendall911/TCIntegrations/assets/44974827/ba8954e5-4cbb-4d28-8715-75b530cf105f)

**Comment by wendall911** [comment]
Ok, I'll get a fix out for this. There have been a lot of changes with the mod in 1.19.2 and I missed a couple things.

**Comment by wendall911** [comment]
Fixed in the latest 1.19.2-2.0.21.6
