### ISSUE TITLE
[1.18.2] Phantasmal modifier bypasses Unbreakable

### ISSUE THREAD

**Issue by KermitEmperor** [wendall911/TCIntegrations#63]
![image](https://github.com/wendall911/TCIntegrations/assets/74988196/66cecd10-931f-4e84-91f3-0ddc2d4c6c88)
Phantasmal modifier bypasses unbreakable modifier by damaging the weapon 1 after swinging, might be present in 1.19

**Comment by KermitEmperor** [comment]
and overslime as well

**Comment by wendall911** [comment]
Ok, got it. I'll take a look and get a fix out soon.

**Comment by wendall911** [comment]
Overslime is supposed to work like that. It is part of TCon. 

The damage for this modifier was intentional as well, as it is VERY overpowered. I feel like it should stay like it is. Edible modifiers work this way as well, like Tasty or Cheesy (from this mod)

**Comment by wendall911** [comment]
Ok, consensus was to make Unbreakable work, since it's overpowered anyhow. I've pushed up an update to curseforge and modrinth. Thanks for the report!
