### ISSUE TITLE
Missing recipes for Molten Forgotten

### ISSUE THREAD

**Issue by SMarriner** [wendall911/TCIntegrations#64]
![image](https://github.com/wendall911/TCIntegrations/assets/54454720/57bddcb7-02a4-4644-97ec-873b57e5c07e)
![image](https://github.com/wendall911/TCIntegrations/assets/54454720/c900ae18-05d3-4776-a67e-bd7510948cfc)
![image](https://github.com/wendall911/TCIntegrations/assets/54454720/662e4b18-9b3b-4329-8bff-5b9278642628)

**Comment by wendall911** [comment]
Thanks for the report. I'll take a look at this soon.

**Comment by wendall911** [comment]
Released in the latest version on CurseForge and Modrinth.
