### ISSUE TITLE
Cant smelt Dragonsteel 

### ISSUE THREAD

**Issue by Koumudes** [wendall911/TCIntegrations#72]
I played this mod in 1.18.2 did this mod can be overlap with other mods? Cuz when i try to smelt dragonsteel in basic seared smelter i cant. The item cannot be molten. Or there's no ice and fire dragon integration in 1.18.2?

**Comment by wendall911** [comment]
This is not a materials mod, other than a couple exceptions. Install JEI and look for uses for dragonsteel and other stuff, you'll see there are several modifiers that provide capabilities. It is also in the mod description.

**Comment by Koumudes** [comment]
but there's written "Adds Fire/Ice/Thunder Dragonsteel to smeltery" in curseforge. so what do you mean with that?

**Comment by wendall911** [comment]
Oh, right. I see what you are saying. I will take a look. Sorry about that.

**Comment by Koumudes** [comment]
No problem, thanks for the response

**Comment by wendall911** [comment]
This is working just fine. Did you check JEI? It clearly shows you need to use Blazing Blood to smelt any of the dragonsteel stuff. Only thing that doesn't work is making nuggets, and that's because there isn't an item in IFD for dragonsteel nuggets.
