### ISSUE TITLE
[1.18.2] Melting support for multiple things

### ISSUE THREAD

**Issue by vizthex123** [wendall911/TCIntegrations#73]
Adding them to 1.19.2 would be great too.

- Ender Pearl Dust
- Diamond and Emerald Dusts
- Diamond and Emerald Nuggets (you can make them melt into 11 mB since Tinker's makes Gems give 100)
- (Nether) Quartz Dust (tags just refer to it as `quartz` though)
- Quark's Glass Shards (and add the `forge:glass/silica` tag to Dirty Glass so Tinker's auto-adds the recipes. Same goes for Create's Framed Glass & Panes)

**Comment by wendall911** [comment]
This is not a materials mod, it is an integrations mod. I'm not sure what the purpose of these are?

**Comment by vizthex123** [comment]
Part of integration is adding melting recipes for things, otherwise it's only halfway integrated.

Plus, this is kinda the only integration mod around lol.

I would just make it a mod - but Java is hellish, so I'd never be able to learn it.
