### ISSUE TITLE
Elementus Integration

### ISSUE THREAD

**Issue by SpicyMayo9** [wendall911/TCIntegrations#74]
The mod has steel as one of the materials it adds to your game, but when put with Tinkers Construct it doesn't seem to corporate it into something you can make it with through alloying. With that being the main reason though, it would also be nice to add the other two materials the mod has, Anthekite and Diarkrite, as materials as well to be used in tinkering as well.

**Comment by wendall911** [comment]
This isn't a materials mod, but an integrations mod. So unless there is some specific purpose for the material to replicate some behavior, then it is far outside of the scope.
